# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a05d5ec9d345140f0279f4e6b4af7d9151e428bcd0ffd287a44f3a04fb0c3d2955034a62d402a3f575d26980ec09981a9ce85d9630ec4b313f2b0500091139
  service_credentials_key: 5c8665f33a888b606bd54563e3b4e7d339dc7f2806854d46c3d7c80a002ea102ef4d52709abe59036a7d7b270252a596646398a2f01889b3f07d256a515ed744

test:
  secret_key_base: ff6e25fe12ff1aaea8bfa6d02b685cd6fd925041dda4cea066ccd60198fb135e4f4edb50800332d8d41a89c65bbca309d1ad229e9a23c7a08a78439c9b4dfba5
  service_credentials_key: 5c8665f33a888b606bd54563e3b4e7d339dc7f2806854d46c3d7c80a002ea102ef4d52709abe59036a7d7b270252a596646398a2f01889b3f07d256a515ed744

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= Rails.env.staging? and ENV.fetch("SECRET_KEY_BASE") %>
  service_credentials_key: <%= Rails.env.staging? and ENV.fetch("SERVICE_CREDENTIALS_ENCRYPTION_KEY") %>

production:
  secret_key_base: <%= Rails.env.production? and ENV.fetch("SECRET_KEY_BASE") %>
  service_credentials_key: <%= Rails.env.production? and ENV.fetch("SERVICE_CREDENTIALS_ENCRYPTION_KEY") %>
